### Single neuron using Numpy

In [1]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = np.dot(inputs, weights) + bias
print(output)

4.8


### Layer of Neurons using numpy

In [7]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]


layer_output = np.dot(weights, inputs) + biases # Here we did weights * inputs so as to match the dimensions of the resultant matrix
#layer_output = np.dot(inputs, np.array(weights).T) + biases (Same output as above Line)
print(layer_output)

[4.8   1.21  2.385]


### Batches of Neurons

In [8]:
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
# here we have taken lists of list as input 
Batch_output = np.dot(inputs, np.array(weights).T) + biases
print(Batch_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
